//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.02 at 03:05:25 PM EDT 
//


package com.osbitools.ws.wp.shared.binding;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WebWidgets complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WebWidgets">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="wwg_container" type="{}WebWidgetContainer"/>
 *           &lt;element name="wwg_chart" type="{}WebWidgetChart"/>
 *           &lt;element name="wwg_control" type="{}WebWidgetControl"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WebWidgets", propOrder = {
    "wwgContainerOrWwgChartOrWwgControl"
})
public class WebWidgets {

    @XmlElements({
        @XmlElement(name = "wwg_container", type = WebWidgetContainer.class),
        @XmlElement(name = "wwg_chart", type = WebWidgetChart.class),
        @XmlElement(name = "wwg_control", type = WebWidgetControl.class)
    })
    protected List<WebWidget> wwgContainerOrWwgChartOrWwgControl;

    /**
     * Gets the value of the wwgContainerOrWwgChartOrWwgControl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wwgContainerOrWwgChartOrWwgControl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWwgContainerOrWwgChartOrWwgControl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WebWidgetContainer }
     * {@link WebWidgetChart }
     * {@link WebWidgetControl }
     * 
     * 
     */
    public List<WebWidget> getWwgContainerOrWwgChartOrWwgControl() {
        if (wwgContainerOrWwgChartOrWwgControl == null) {
            wwgContainerOrWwgChartOrWwgControl = new ArrayList<WebWidget>();
        }
        return this.wwgContainerOrWwgChartOrWwgControl;
    }

}
