//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.02 at 03:05:25 PM EDT 
//


package com.osbitools.ws.wp.shared.binding;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WebWidgetContainer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WebWidgetContainer">
 *   &lt;complexContent>
 *     &lt;extension base="{}WebWidget">
 *       &lt;sequence>
 *         &lt;element name="wwg_list" type="{}WebWidgets" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WebWidgetContainer", propOrder = {
    "wwgList"
})
public class WebWidgetContainer
    extends WebWidget
{

    @XmlElement(name = "wwg_list")
    protected WebWidgets wwgList;

    /**
     * Gets the value of the wwgList property.
     * 
     * @return
     *     possible object is
     *     {@link WebWidgets }
     *     
     */
    public WebWidgets getWwgList() {
        return wwgList;
    }

    /**
     * Sets the value of the wwgList property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebWidgets }
     *     
     */
    public void setWwgList(WebWidgets value) {
        this.wwgList = value;
    }

}
